FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update  && apt-get install -y build-essential libboost-all-dev zlib1g-dev zlib1g git
RUN git clone https://github.com/BioDepot/LINCS_RNAseq_cpp.git
RUN cp -r LINCS_RNAseq_cpp/source /source
RUN cd source && make clean && make all96  STATIC=1 SSE2=1 &&  make clean && make all384  STATIC=1 SSE2=1
