FROM alpine:3.10
RUN apk update upgrade --no-cache && apk add build-base boost-dev zlib zlib-dev git
RUN git clone https://github.com/BioDepot/LINCS_RNAseq_cpp.git
RUN cp -r LINCS_RNAseq_cpp/source /source
RUN cd source && make clean && make all96  STATIC=1 SSE2=1 ALPINE=1 &&  make clean && make all384  STATIC=1 SSE2=1 ALPINE=1
