FROM biodepot/dtoxs_analysis:1.0__ubuntu_18.04__bioc-3.7__r_3.5.1__7d8341e2_old
RUN rm -r $HOME/Programs/
RUN rm -r $HOME/Scripts
# Add input directories/files
ADD Programs/ $HOME/Programs/
ADD Scripts/ $HOME/Scripts/
