FROM debian:buster-slim
RUN apt-get update && apt-get install -y  build-essential git-core cmake zlib1g-dev libncurses-dev wget 
RUN wget -c  https://github.com/genome/somatic-sniper/archive/v1.0.5.0.tar.gz -O - | tar -xz
RUN cd somatic-sniper* && cmake . && make deps && make -j && make install
